### ISSUE TITLE
How to get figure 13 & 14 "Time & Training speedup in the multi-GPU scenario"?

### ISSUE THREAD

**Issue by VoidStardust** [sands-lab/omnireduce-experiments#1]
Hello,

I'm trying to reproduce the experimental results of OmniReduce in the multi-GPU scenario as described in Section 6.3 of the OmniReduce paper.

It seems that OmniReduce [pytorch patch](https://github.com/sands-lab/omnireduce/blob/dafb1130bf66da2028fb093b333f1ca9a89c5049/omnireduce-RDMA/frameworks_integration/pytorch_patch/omnireduce-pytorch.patch#L92-L110) does not support multi-GPU, because OmniReduce only aggregate `inputs[0]` from all input tensors `std::vector<at::Tensor>& inputs`. So I wonder how you got Figure 13 & 14 in your SIGCOMM '21 paper.

Looking forward to your reply, thanks.

Alex

**Comment by Phlix1** [comment]
Hi Alex,

The multi-GPU version OmniReduce was not merged into the master branch.

You can access this version from this [branch](https://github.com/Phlix1/omnireduce/tree/hierarchical).

To run the multi-GPU version OmniReduce, you just need to add `ndev` in the _omnireduce.cfg_ file which refers to the GPUs in single machine. You also need NCCL environment as NCCL will be used for intra-server multi-GPU reduction and broadcast in this version.

Jiawei

**Comment by VoidStardust** [comment]
Hello,

Thanks for your reply. I have successfully run the hierarchical version of OmniReduce. I will share my results in the new repo.

Happy New Year
Alex
